apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:yNgfEQenoJJ8bJZ83KQMw2S8KasOzb3OwFdXZKyy7q3OO28a3mv0fPxyRvwDq1PymMSaR1jP7xv83bYW0x7TSFsqEXfuvT9rtMvB0cR+1Kt5l/Tq6lM4GFKOMyiXArYLmw/RTWtfDivsrY6Cw0A+s9Pk7ZOFpGcuBvIBjJ7hvgfBl7HtygBIPxD2ecbzDMK0lFlAv/jCGMHo7XgTB1aaHFQvq41Usc/ProH8TTugPM3Ydo3eLcs/shel3SbuAmLMLM/hQYoA+TJcvJr41XiRsuzjifSCiWt4,iv:jQp6WEhNAAQaRAE9bixO5V0yehgPNgh1iIt5pn3laFI=,tag:D4aRf5wgr9FOPN3AHeLA+A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - recipient: age10909nkppr57y68wrcvns3xusfjv5pghtfk9v2kuh7zgv3nun74hqecr74v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQTRJL0NkSXNYNnppdUVR
            Qk94QUJIYm0wYllyWGFXa2drQ05CWER6TVVvCitHRnRhc3FBdVo4dlRKY0F4cldu
            bkVMU0tHWlFWTlhiaktFZDhXWVpxWmsKLS0tIGl2c2thQW1uTEtWUGlpU0lqaTQx
            d0ZUTVJzMVk0OTlNa2VZUXl2c2hncHcKLRbz18OXg2o8n5CAF6eY4VDOm8/lGWX4
            jo2tJ+qGoTcU5mKFBF+ssfabF6E88sGwv8GUtmPTuKTEGERfep8L4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T18:33:22Z"
    mac: ENC[AES256_GCM,data:9PfCrmq/gv4wotHvlhwQayF5dGi02taY430GfDzQWVNm2Z0pGhP81NcgAqGWru0G0zMmpOGSFqXbGOhW/a8YsnTCuj2ffBsPn6wugbB/+7wYKMDrjAUqmzl7RIECjcw5V5TZd3j16EU7Ue9OdW2q1yHpU/URUiBqn/6F8zNnYHU=,iv:blw6iHw71Pqzc9Ihd+NUOmDhLMlq4T83jQAmJt6tJbE=,tag:y0SgTc6DSu24VTgouQhL4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
