apiVersion: v1
kind: PersistentVolumeClaim  
metadata:
  name: abs-audiobooks-pvc      
spec:
  accessModes:
    - ReadWriteOnce          
  resources:                 
    requests:
      storage: 3Gi         
  # storageClassName: local-path # This is the default for Rancher Desktop/k3s.
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-podcasts-pvc
  namespace: audiobookshelf
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-metadata-pvc
  namespace: audiobookshelf
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-config-pvc
  namespace: audiobookshelf
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi 
